name = "Tinkerer's Quilt Custom (1.20)"
author = "Sisby folk"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bbe9920f879c065fa9229e0ab2f5001ae0609589ef1f88e72c0e0bf087f7b57"

[versions]
minecraft = "1.20.1"
quilt = "0.29.2"
unsup = "1.2.0-pre3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "/resources/datapacks/"
resourcepack-folder = "/resources/resourcepacks/"
