name = "Tinkerer's Quilt Custom (1.20)"
author = "Sisby folk"
version = "4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "386106b920dccdf5f72ebda88e74e515d19ad4d41ef50c9ebbca7a27b9ccf9bd"

[versions]
minecraft = "1.20.1"
quilt = "0.29.2"
unsup = "1.2.0-pre3"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
datapack-folder = "/resources/datapacks/"
resourcepack-folder = "/resources/resourcepacks/"
